pipeline {
  agent { label 'build' }

  parameters {
    string(name: 'IMAGETAG', defaultValue: 'latest', description: 'Docker Image Tag')
  }

  environment {
    CD_REPO = "git@gitlab.com:r1zzg0d-projects/automated-devsecops-pipeline/devsecops-cd-pipeline.git"
    IMAGE_NAME = "r1zzg0d/devsecops-pipeline"
  }

  stages {

    stage('Checkout CD Repo') {
      steps {
        git branch: 'main',
            credentialsId: 'GitlabCred',
            url: "${CD_REPO}"
      }
    }

    stage('Update Deployment Image') {
      steps {
        sh """
          sed -i 's|image:.*|image: r1zzg0d/devsecops-pipeline:${params.IMAGETAG}|g' kubernetes/deployment.yml
        """
      }
    }

    stage('Commit & Push Changes') {
      steps {
        withCredentials([sshUserPrivateKey(credentialsId: 'GitlabCred', keyFileVariable: 'SSH_KEY')]) {
          sh """
            export GIT_SSH_COMMAND="ssh -i $SSH_KEY -o StrictHostKeyChecking=no"
            git config user.email "jenkins@devsecops.com"
            git config user.name "Jenkins"
            git add .
            git commit -m "Updated image to r1zzg0d/devsecops-pipeline:${params.IMAGETAG}" || echo "No changes to commit"
            git push origin main
          """
        }
      }
    }
  }
}